### ISSUE TITLE
ERROR: cannot launch node of type [chisel_ros/ChiselNode]: can't locate node [ChiselNode] in package [chisel_ros]

### ISSUE THREAD

**Issue by Janani-Mohan** [personalrobotics/OpenChisel#18]
Hello ,

I am unable to execute the launch file as I am encountering the following error. 
ERROR: cannot launch node of type [chisel_ros/ChiselNode]: can't locate node [ChiselNode] in package [chisel_ros]

The build is through without any errors. Can anyone guide me on how to fix this error ?

Thanks a lot.

Best regards,
Janani

**Comment by lhanaf** [comment]
Dear Janani,
    I meet the same problems, how did you solve this problem?

Best Regards

**Comment by taihup** [comment]
The same issue here, How did you solve it?

**Comment by taihup** [comment]
I solved it by running:

```
source /opt/ros/kinetic/setup.bash
source ~/catkin_ws/devel/setup.bash
export ROS_PACKAGE_PATH=~/catkin_ws:${ROS_PACKAGE_PATH}
export CURRENT_CMAKE_BUILD_DIR="$(catkin locate --workspace ~/catkin_ws --build)"
```
