### ISSUE TITLE
Error in hash function - p3 = 8349279; should be p3 = 83492791; according to paper

### ISSUE THREAD

**Issue by moloned** [personalrobotics/OpenChisel#19]
// https://github.com/personalrobotics/OpenChisel/blob/master/open_chisel/include/open_chisel/ChunkManager.h
//
// Spatial hashing function from Matthias Teschner
// Optimized Spatial Hashing for Collision Detection of Deformable Objects
struct ChunkHasher {
	// Three large primes are used for spatial hashing.
	static constexpr size_t p1 = 73856093;
	static constexpr size_t p2 = 19349663;
	static constexpr size_t p3 = 8349279;

	std::size_t operator()(const ChunkID& key) const {
		return (key(0) * p1 ^ key(1) * p2 ^ key(2) * p3);
	}
};

**Comment by mklingen** [comment]
Ok fixed.

**Comment by moloned** [comment]
Actually despite what it says in the literature 19349663 isn't prime (it's the product of 41 and 471943)

**Comment by mklingen** [comment]
That's what I get for trusting the literature to pick large primes. Shall we find 3 better ones?

**Comment by dcanelhas** [comment]
The number:
73856093 is prime;
19349663 is not prime, but 19349653 and 19349669 are (one smaller and one larger);
83492791 is prime.

source: http://www.bigprimes.net/primalitytest/
