### ISSUE TITLE
How to get triangle vertices of the OpenChisel mesh ?

### ISSUE THREAD

**Issue by Janani-Mohan** [personalrobotics/OpenChisel#20]
Hello,

I would like to know how to get the triangle vertices of the mesh generated by OpenChisel. I am working on Image texturing the mesh generated by OpenChisel to get better quality mesh visually.

It would be great if you can support me with this query.

Thanks,
Janani

**Comment by HubertYang** [comment]
You can get point cloud and color using the Chisel::SaveAllMeshesToPLY
