### ISSUE TITLE
Fixed Frame [map] does not exist when running with Freiburg RGBD dataset

### ISSUE THREAD

**Issue by btyu** [personalrobotics/OpenChisel#23]
When I launch the launch_freiburg_dataset.launch with the rosbag "rgbd_dataset_freiburg3_long_office_household.bag", the rviz report error:
no tf data. Fixed Frame [map] does not exist.

I didn't edit the launch file. It seems that no tf data can be found or no tf frame is set. Meanwhile, there is nothing shown in the rviz as expected, except the grid. How can I fix it? Thanks a lot.

**Comment by mklingen** [comment]
Check the list of frames in RVIZ [http://wiki.ros.org/rviz/UserGuide](url) what frames are available?

**Comment by btyu** [comment]
Thank you for your reply. I don't know how exactly to check the list of frames but maybe it's:
- kinect
- openni_camera
- openni_depth_frame
- openni_depth_optical_frame
- openni_rgb_frame
- openni_rgb_optical_frame
- world

In the launch file, "base_transform" is set to "/world", but the rviz shows "Fixed Frame [map] does not exist". When I try to change the text into "/world" or other text, it changes back soon. When I run `rosrun tf static_transform_publisher 0.0 0.0 0.0 0.0 0.0 1.0 map world 100` as [this](https://answers.ros.org/question/221329/rviz-fixed-frame-map-does-not-exist/?answer=221357) suggests, the Fixed Frame becomes "OK" in rviz, and when I run `rosrun tf view_frames`, the generated pdf starts to show something like [this](https://drive.google.com/open?id=1aLx0NVwMMzAz2wVhtf5fEUwLhu7wcX05). However, still nothing appears in the 3D space of rviz. 

I am new to rviz and ros. I don't know how to solve the problem. Thanx a lot ;)

**Comment by mklingen** [comment]
I believe that the launch file I gave you should be publishing things in `world` frame. There is no map frame.  set the fixed frame in RVIZ to `world`. Then add topics for the chisel mesh (it's of type `Marker`) and other topics published by chisel to see the output.

**Comment by btyu** [comment]
Thank you. I guess I ignored the setting of fixed frame, and didn't add the marker so I didn't see anything. Thanks a lot! Now it works.
